data:
  dataset_path: /path/to/dataset.csv
  train_test_split 0.8
  normalize: truee

model:
type: neural_network
  layers
    - 128
      64
   - 32
  activation_function relu

training
  epochs: 100
  batch_size 32
  learning_rate: 0.001