data:
  dataset_path: /path/to/dataset.csv
  train_test_split: 0.8
  normalize: true

model:
  type: neural_network
  activation_function: relu
  layers:
    - 128
    - 64
    - 32
  
training:
  epochs: 100
  batch_size: 32
  learning_rate: 0.001